# Generated by Django 6.0.3 on 2026-08-11 13:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('arcana', models.CharField(max_length=50)),
                ('suit', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(default=0)),
                ('image_url', models.URLField(max_length=500)),
                ('keywords', models.JSONField(default=list)),
                ('upright_meaning', models.TextField()),
                ('reversed_meaning', models.TextField()),
                ('general_meaning', models.TextField(blank=True)),
                ('relationship_meaning', models.TextField(blank=True)),
                ('career_meaning', models.TextField(blank=True)),
                ('personal_growth_meaning', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TarotReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(max_length=100)),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_interpretation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarot_readings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarotReadingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('orientation', models.CharField(max_length=50)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tarotcard')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.tarotreading')),
            ],
        ),
    ]
