# Generated by Django 6.0.3 on 2026-08-11 13:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tarotcard_tarotreading_tarotreadingcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterpretation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=50)),
                ('input_hash', models.CharField(max_length=255)),
                ('response_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
