# Generated by Django 6.1 on 2026-08-11 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aiinterpretation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(default='combined', max_length=100)),
                ('question', models.TextField(blank=True, null=True)),
                ('palm_features', models.JSONField(blank=True, null=True)),
                ('palm_interpretation', models.JSONField(blank=True, null=True)),
                ('synthesis_interpretation', models.JSONField(blank=True, null=True)),
                ('overall_insight', models.TextField(blank=True, null=True)),
                ('reading_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('palm_completed', 'Palm Completed'), ('tarot_completed', 'Tarot Completed'), ('ai_completed', 'AI Completed'), ('report_generated', 'Report Generated'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('pdf_report_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tarot_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tarotreading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
