/**
 * Recommendation Engine.
 * Evaluates calculated personality scores to generate personalized advices, suggestions, and tips.
 */

/**
 * Generates recommendations based on personality scores.
 * @param {Object} scores - Numeric scores generated by the personalityEngine
 * @returns {Object} JSON report
 */
exports.generateRecommendations = async (scores = {}) => {
  const {
    leadership = 50,
    creativity = 50,
    emotionalIntelligence = 50,
    communication = 50,
    decisionMaking = 50,
    patience = 50,
    confidence = 50,
    adaptability = 50
  } = scores;

  // Curate dynamic lists based on threshold metrics
  const careerRecommendations = [];
  const learningRecommendations = [];
  const lifestyleRecommendations = [];
  const relationshipAdvice = [];
  const healthTips = [];
  const dailyHabits = [];

  // 1. CAREER RECOMMENDATIONS (Focus on highest score strengths)
  if (leadership >= 65) {
    careerRecommendations.push("Leadership roles: Team Lead, Program Manager, Operations Director.");
  }
  if (creativity >= 65) {
    careerRecommendations.push("Creative paths: Product Designer, Content Director, Innovation Architect.");
  }
  if (decisionMaking >= 65) {
    careerRecommendations.push("Strategic roles: Business Analyst, Data Scientist, Management Consultant.");
  }
  if (communication >= 65) {
    careerRecommendations.push("Expressive roles: Public Relations Manager, Sales Strategist, Corporate Trainer.");
  }
  if (emotionalIntelligence >= 65 && patience >= 65) {
    careerRecommendations.push("Empathetic roles: Clinical Therapist, HR Partner, Customer Success Specialist.");
  }
  // Fallbacks if scores are moderate/flat
  if (careerRecommendations.length < 2) {
    careerRecommendations.push("Collaborative roles: Project Coordinator, Scrum Master, Cross-functional Liaison.");
    careerRecommendations.push("Operational Specialist: Systems Administrator, Quality Assurance Lead.");
  }

  // 2. LEARNING RECOMMENDATIONS (Focus on growth areas - low scores, or enhancing high scores)
  if (communication < 50) {
    learningRecommendations.push("Course: Public Speaking & Assertiveness Training (e.g., Toastmasters).");
  } else {
    learningRecommendations.push("Workshop: Advanced Persuasion, Negotiation, and Executive Presence.");
  }
  if (decisionMaking < 50) {
    learningRecommendations.push("Skill development: Critical Thinking & Decisive Frameworks.");
  } else {
    learningRecommendations.push("Advanced study: Game Theory or Strategic Operations Planning.");
  }
  if (creativity < 50) {
    learningRecommendations.push("Practice: Lateral Thinking techniques & Creative Problem-Solving workshops.");
  } else {
    learningRecommendations.push("Explore: Generative UI Design or creative storytelling programs.");
  }
  if (emotionalIntelligence < 55) {
    learningRecommendations.push("Read: Emotional Intelligence 2.0 & active empathy workshops.");
  }

  // 3. RELATIONSHIP ADVICE
  if (emotionalIntelligence < 50) {
    relationshipAdvice.push("Practice active listening: repeat back what you hear before sharing your view.");
    relationshipAdvice.push("Schedule weekly validation checks to ensure emotional needs are acknowledged.");
  } else {
    relationshipAdvice.push("Practice healthy boundary setting: avoid absorbing everyone else's emotional weight.");
    relationshipAdvice.push("Use your strong empathy to mentor or support peer groups in a structured way.");
  }
  if (patience < 50) {
    relationshipAdvice.push("Pause for 10 seconds before reacting during high-conflict discussions.");
  }
  if (communication < 50) {
    relationshipAdvice.push("Use explicit 'I feel' statements instead of assuming others read your silence.");
  }

  // 4. HEALTH SUGGESTIONS
  if (confidence >= 70 && leadership >= 70) {
    healthTips.push("Pace your physical workouts to protect joint vitality and prevent high-stress burnout.");
    healthTips.push("Introduce restorative yoga or stretching to quiet active muscle tension.");
  } else {
    healthTips.push("Engage in consistent, moderate cardiovascular exercise to boost active daily energy.");
  }
  if (patience < 50) {
    healthTips.push("Introduce 10 minutes of deep box-breathing to lower cortisol levels and calm heart rate.");
  } else {
    healthTips.push("Incorporate rhythmic swimming or long-distance walking to maintain muscular tone.");
  }
  healthTips.push("Ensure adequate hydration and regular circadian sleep patterns.");

  // 5. LIFESTYLE SUGGESTIONS
  if (adaptability < 50) {
    lifestyleRecommendations.push("Intentionally shake up your routine: take a new route home, or try a different hobby.");
    lifestyleRecommendations.push("Minimalist clutter clearance: simplify your immediate physical workspace.");
  } else {
    lifestyleRecommendations.push("Maintain a structured weekly planner to prevent high adaptability from turning into chaos.");
    lifestyleRecommendations.push("Designate a distraction-free timezone in the evening to allow mental reset.");
  }
  if (creativity >= 60) {
    lifestyleRecommendations.push("Maintain a designated space in your home solely for creative flow (writing, drawing).");
  }

  // 6. DAILY HABITS
  if (confidence < 50) {
    dailyHabits.push("Morning ritual: write down 3 personal wins from the previous day before opening your phone.");
  } else {
    dailyHabits.push("Gratitude logging: identify 3 people who helped you, and thank them directly.");
  }
  if (patience < 55) {
    dailyHabits.push("No-device eating: eat at least one meal a day fully present, without digital distractions.");
  } else {
    dailyHabits.push("Digital detox: set a hard power-down for all screens 45 minutes before sleep.");
  }
  dailyHabits.push("Morning hydration: drink a tall glass of water immediately upon waking.");

  return {
    careerRecommendations: careerRecommendations.slice(0, 3),
    learningRecommendations: learningRecommendations.slice(0, 3),
    lifestyleRecommendations: lifestyleRecommendations.slice(0, 3),
    relationshipAdvice: relationshipAdvice.slice(0, 3),
    healthTips: healthTips.slice(0, 3),
    dailyHabits: dailyHabits.slice(0, 3)
  };
};
