import io
from datetime import datetime
from typing import Any, Dict, Optional
from fpdf import FPDF
import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from app.schemas.reading import FullReading


class PDFReport(FPDF):
    """Styled PDF Generator for Palmistry & Tarot Intelligence Platform."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(120, 110, 140)
        self.cell(0, 8, "PALMISTRY & TAROT INTELLIGENCE PLATFORM", border=0, align="L")
        self.cell(0, 8, "CONFIDENTIAL & SACRED", border=0, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(220, 215, 230)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 145, 160)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by Cosmic Oracle AI", align="C")


def clean_text(text: Optional[str]) -> str:
    """Sanitizes text for standard Latin-1 PDF encoding."""
    if not text:
        return ""
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "--",
        "\u2022": "-",
        "\u2026": "...",
        "\u00a0": " ",
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Ensure text is encodable in latin-1
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_pdf_report(reading: FullReading, user_name: str = "Seeker") -> bytes:
    """Generates a complete multi-page PDF report as raw bytes."""
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title Banner
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 10, clean_text("Holistic Reading Synthesis & Life Map"), align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 95, 120)
    date_str = reading.date[:10] if reading.date else datetime.utcnow().strftime("%Y-%m-%d")
    pdf.cell(0, 6, clean_text(f"Prepared for: {user_name}  |  Reading ID: {reading.id}  |  Date: {date_str}"), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Insight Score Banner Box
    pdf.set_fill_color(245, 243, 252)
    pdf.set_draw_color(190, 180, 220)
    pdf.rect(10, pdf.get_y(), 190, 24, style="FD")

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(50, 40, 80)
    pdf.cell(95, 8, clean_text(f"Overall Insight Score: {reading.insight_score.overall}%"), align="L")
    pdf.cell(95, 8, clean_text(f"Tier: {reading.insight_score.tier}"), align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 75, 95)
    score_sub = (
        f"Palm Biometrics: {reading.insight_score.palm_confidence}%  |  "
        f"Tarot Synergy: {reading.insight_score.tarot_relevance}%  |  "
        f"Personality Alignment: {reading.insight_score.personality_alignment}%  |  "
        f"Consistency: {reading.insight_score.consistency}%"
    )
    pdf.cell(190, 6, clean_text(score_sub), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # 1. Executive Narrative Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, "1. Executive Spiritual Synthesis", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 55, 75)
    pdf.multi_cell(190, 5, clean_text(reading.interpretation.overview_summary), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # 2. Palm Biometric Analysis
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, "2. Palm Biometric & Line Analysis", new_x="LMARGIN", new_y="NEXT")

    palm = reading.palm_result
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, clean_text(f"Hand Constitution: {palm.hand_type}  |  Primary Element: {palm.primary_element}  |  Confidence: {palm.confidence_score}%"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    lines_data = [
        ("Heart Line (Anahata)", palm.lines.heart_line),
        ("Head Line (Manas)", palm.lines.head_line),
        ("Life Line (Prana)", palm.lines.life_line),
    ]
    if palm.lines.fate_line:
        lines_data.append(("Fate Line (Dharma)", palm.lines.fate_line))

    for line_name, line_obj in lines_data:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(60, 50, 90)
        pdf.cell(0, 5, clean_text(f"- {line_name} ({line_obj.length.capitalize()} length, {line_obj.depth.capitalize()} depth)"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(70, 65, 85)
        pdf.multi_cell(190, 4.5, clean_text(f"  Interpretation: {line_obj.summary}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.ln(3)

    # 3. Tarot Archetypal Spread
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, clean_text(f"3. Tarot Spread: {reading.spread_title}"), new_x="LMARGIN", new_y="NEXT")

    for card_drawn in reading.tarot_result.cards:
        orientation_str = "Reversed" if card_drawn.is_reversed else "Upright"
        card = card_drawn.card
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(70, 40, 90)
        pdf.cell(0, 5, clean_text(f"[{card_drawn.position_label}] {card.name} ({orientation_str})"), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 90, 120)
        pdf.cell(0, 4.5, clean_text(f"Position Meaning: {card_drawn.position_meaning}"), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(70, 65, 85)
        meaning_text = card.reversed_meaning if card_drawn.is_reversed else card.upright_meaning
        pdf.multi_cell(190, 4.5, clean_text(f"Archetypal Guidance: {meaning_text}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

    pdf.ln(3)

    # 4. Personality & Archetypal Architecture
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, clean_text("4. Personality & Archetypal Intelligence"), new_x="LMARGIN", new_y="NEXT")

    pers = reading.personality
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(60, 50, 90)
    pdf.cell(0, 5, clean_text(f"Primary Archetype: {pers.primary_archetype}  |  Secondary: {pers.secondary_archetype}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 4.5, clean_text("Core Strengths:"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    for s in pers.core_strengths:
        pdf.cell(0, 4.5, clean_text(f"  + {s}"), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(1)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 4.5, clean_text("Growth Edges & Evolutions:"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    for g in pers.growth_edges:
        pdf.cell(0, 4.5, clean_text(f"  * {g}"), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # 5. Life Trend & Horizon Forecast
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, clean_text("5. Life Trend & Horizon Forecast"), new_x="LMARGIN", new_y="NEXT")

    trend = reading.life_trend
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 5, clean_text(f"Life Path Theme: {trend.life_path_summary}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(70, 65, 85)
    pdf.multi_cell(190, 4.5, clean_text(f"Near-Term Horizon (1-3 Months): {trend.horizon_forecast.near_term}"), new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(190, 4.5, clean_text(f"Mid-Term Horizon (3-12 Months): {trend.horizon_forecast.mid_term}"), new_x="LMARGIN", new_y="NEXT")
    pdf.multi_cell(190, 4.5, clean_text(f"Long-Term Horizon (1-3 Years): {trend.horizon_forecast.long_term}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 6. Actionable Guidance & Daily Mantra
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(40, 30, 70)
    pdf.cell(0, 8, clean_text("6. Actionable Spiritual Guidance"), new_x="LMARGIN", new_y="NEXT")

    recs = reading.recommendations
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(90, 40, 110)
    pdf.cell(0, 6, clean_text(f"Daily Affirmation: \"{recs.daily_mantra}\""), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(70, 65, 85)
    if recs.career:
        pdf.cell(0, 4.5, clean_text(f"Career Focus: {recs.career[0]}"), new_x="LMARGIN", new_y="NEXT")
    if recs.relationships:
        pdf.cell(0, 4.5, clean_text(f"Relational Guidance: {recs.relationships[0]}"), new_x="LMARGIN", new_y="NEXT")
    if recs.growth:
        pdf.cell(0, 4.5, clean_text(f"Personal Growth: {recs.growth[0]}"), new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def generate_excel_report(reading: FullReading, user_name: str = "Seeker") -> bytes:
    """Generates a structured, multi-tab Excel workbook as raw bytes."""
    wb = openpyxl.Workbook()

    # Style constants
    header_fill = PatternFill(start_color="3D2C6A", end_color="3D2C6A", fill_type="solid")
    header_font = Font(name="Arial", size=11, bold=True, color="FFFFFF")
    title_font = Font(name="Arial", size=14, bold=True, color="2C1E4E")
    bold_font = Font(name="Arial", size=10, bold=True)
    normal_font = Font(name="Arial", size=10)
    thin_border = Border(
        left=Side(style="thin", color="E0DFE8"),
        right=Side(style="thin", color="E0DFE8"),
        top=Side(style="thin", color="E0DFE8"),
        bottom=Side(style="thin", color="E0DFE8"),
    )

    # -------------------------------------------------------------
    # Sheet 1: Overview
    # -------------------------------------------------------------
    ws1 = wb.active
    ws1.title = "Overview"

    ws1["A1"] = "Palmistry & Tarot Intelligence Report"
    ws1["A1"].font = title_font
    ws1.append([])

    overview_rows = [
        ("Reading ID", reading.id),
        ("Seeker Name", user_name),
        ("Date Generated", reading.date),
        ("Spread Type", reading.spread_type),
        ("Spread Title", reading.spread_title),
        ("Overall Insight Score", f"{reading.insight_score.overall}%"),
        ("Synthesis Tier", reading.insight_score.tier),
        ("Palm Confidence Sub-Score", f"{reading.insight_score.palm_confidence}%"),
        ("Tarot Relevance Sub-Score", f"{reading.insight_score.tarot_relevance}%"),
        ("Personality Alignment Sub-Score", f"{reading.insight_score.personality_alignment}%"),
        ("Context Relevance Sub-Score", f"{reading.insight_score.context_relevance}%"),
        ("Consistency Sub-Score", f"{reading.insight_score.consistency}%"),
    ]

    for label, val in overview_rows:
        ws1.append([label, str(val)])

    ws1.append([])
    ws1.append(["Executive Narrative Summary"])
    ws1.append([reading.interpretation.overview_summary])

    # -------------------------------------------------------------
    # Sheet 2: Palm Biometrics
    # -------------------------------------------------------------
    ws2 = wb.create_sheet("Palm Biometrics")
    ws2.append(["Line Name", "Length", "Depth", "Curvature", "Confidence", "Interpretation Summary"])
    for cell in ws2[1]:
        cell.fill = header_fill
        cell.font = header_font

    lines = [
        ("Heart Line", reading.palm_result.lines.heart_line),
        ("Head Line", reading.palm_result.lines.head_line),
        ("Life Line", reading.palm_result.lines.life_line),
    ]
    if reading.palm_result.lines.fate_line:
        lines.append(("Fate Line", reading.palm_result.lines.fate_line))

    for name, line_data in lines:
        ws2.append([
            name,
            line_data.length,
            line_data.depth,
            line_data.curvature,
            f"{line_data.confidence}%",
            line_data.summary,
        ])

    # -------------------------------------------------------------
    # Sheet 3: Tarot Spread
    # -------------------------------------------------------------
    ws3 = wb.create_sheet("Tarot Spread")
    ws3.append(["Position Index", "Position Label", "Position Meaning", "Card Name", "Orientation", "Arcana", "Suit", "Keywords", "Archetypal Meaning"])
    for cell in ws3[1]:
        cell.fill = header_fill
        cell.font = header_font

    for card_drawn in reading.tarot_result.cards:
        c = card_drawn.card
        meaning_text = c.reversed_meaning if card_drawn.is_reversed else c.upright_meaning
        ws3.append([
            card_drawn.position_index + 1,
            card_drawn.position_label,
            card_drawn.position_meaning,
            c.name,
            "Reversed" if card_drawn.is_reversed else "Upright",
            c.arcana,
            c.suit or "Trump",
            ", ".join(c.keywords),
            meaning_text,
        ])

    # -------------------------------------------------------------
    # Sheet 4: Categories & Recommendations
    # -------------------------------------------------------------
    ws4 = wb.create_sheet("Guidance & Actions")
    ws4.append(["Category Title", "Score", "Summary Narrative", "Key Takeaways"])
    for cell in ws4[1]:
        cell.fill = header_fill
        cell.font = header_font

    for cat in reading.interpretation.categories:
        ws4.append([
            cat.title,
            f"{cat.score}%",
            cat.detailed_narrative,
            " | ".join(cat.key_takeaways),
        ])

    # Auto-adjust column widths
    for ws in [ws1, ws2, ws3, ws4]:
        for col in ws.columns:
            max_len = max(len(str(cell.value or "")) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = min(max_len + 4, 60)

    output = io.BytesIO()
    wb.save(output)
    return output.getvalue()
