"""Initial tables: users and readings

Revision ID: 10c670de1026
Revises: 
Create Date: 2026-08-20 11:05:20.378930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c670de1026'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('age_group', sa.String(length=32), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('spiritual_goals', sa.JSON(), nullable=False),
    sa.Column('reading_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spread_type', sa.String(length=64), nullable=False),
    sa.Column('spread_title', sa.String(length=255), nullable=False),
    sa.Column('palm_result', sa.JSON(), nullable=False),
    sa.Column('tarot_spread', sa.JSON(), nullable=False),
    sa.Column('user_context', sa.JSON(), nullable=True),
    sa.Column('interpretation', sa.JSON(), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('life_trend', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('insight_score', sa.JSON(), nullable=False),
    sa.Column('pdf_url', sa.String(length=512), nullable=True),
    sa.Column('excel_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_index(op.f('ix_readings_user_id'), 'readings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readings_user_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
