from pathlib import Path
import json
import shutil
import subprocess
import sys
import uuid

from fastapi import UploadFile


BASE_DIR = Path(__file__).resolve().parents[1]

PALM_CODE_DIR = BASE_DIR / "palmistry" / "code"
INPUT_DIR = PALM_CODE_DIR / "input"
RESULTS_DIR = PALM_CODE_DIR / "results"

INPUT_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)


def parse_measurements(measurements):
    """
    Convert the repository's flat measurement list into
    structured information for the frontend.
    """

    if not isinstance(measurements, list):
        return {
            "heart_line": None,
            "head_line": None,
            "life_line": None,
        }

    return {
        "heart_line": {
            "title": "Heart Line",
            "finding": "Short",
            "description": measurements[0]
            if len(measurements) > 0
            else "",
            "interpretation": measurements[1]
            if len(measurements) > 1
            else "",
        },

        "head_line": {
            "title": "Head Line",
            "finding": "Short",
            "description": measurements[2]
            if len(measurements) > 2
            else "",
            "interpretation": measurements[3]
            if len(measurements) > 3
            else "",
        },

        "life_line": {
            "title": "Life Line",
            "finding": "Short",
            "description": measurements[4]
            if len(measurements) > 4
            else "",
            "interpretation": measurements[5]
            if len(measurements) > 5
            else "",
        },
    }


async def analyze_palm(file: UploadFile):

    extension = Path(file.filename or "").suffix.lower()

    if extension not in [
        ".jpg",
        ".jpeg",
        ".png",
        ".webp",
        ".heic",
    ]:
        extension = ".jpg"

    unique_name = f"api_{uuid.uuid4().hex}{extension}"

    input_path = INPUT_DIR / unique_name

    # Save uploaded image
    with input_path.open("wb") as buffer:
        shutil.copyfileobj(file.file, buffer)

    command = [
        sys.executable,
        "read_palm.py",
        "--input",
        unique_name,
    ]

    analysis_json_path = RESULTS_DIR / "palm_analysis.json"

    try:

        process = subprocess.run(
            command,
            cwd=PALM_CODE_DIR,
            capture_output=True,
            text=True,
            timeout=120,
        )

        if process.returncode != 0:

            raise RuntimeError(
                process.stderr[-4000:]
                if process.stderr
                else "Palm analysis process failed."
            )

        if not analysis_json_path.exists():

            raise RuntimeError(
                "Palm analysis completed, but "
                "palm_analysis.json was not generated."
            )

        # --------------------------------------------------
        # Read structured result generated by read_palm.py
        # --------------------------------------------------

        with analysis_json_path.open(
            "r",
            encoding="utf-8"
        ) as json_file:

            analysis = json.load(json_file)

        measurements = analysis.get(
            "measurements",
            []
        )

        palm_reading = parse_measurements(
            measurements
        )

        return {

            "success": True,

            "message": (
                "Palm analysis completed successfully."
            ),

            # Keep this temporarily for compatibility.
            "result_image": "/api/palm/result",

            # New frontend image
            "palm_image": "/api/palm/image",

            # Optional detected-line visualization
            "line_image": "/api/palm/lines",

            "filename": unique_name,

            "palm_reading": palm_reading,

            "engine": {
                "detected_lines": analysis.get(
                    "detected_lines",
                    []
                ),

                "measurements": measurements,
            },

        }

    finally:

        # Remove uploaded temporary file.
        if input_path.exists():
            input_path.unlink()