import { SpreadConfig, TarotCardData } from '@/types';

export const SPIRITUAL_INTERESTS_OPTIONS = [
  'Vedic Palmistry & Hastarekha',
  'Hermetic Tarot & Kabbalah',
  'Western Astrology & Transits',
  'Archetypal Psychology (Jungian)',
  'Chakra & Bio-Energy Harmonization',
  'Cosmic Numerology',
  'Dream Archetype Analysis',
  'Mindfulness & Alchemical Meditation',
];

export const SPIRITUAL_GOALS_OPTIONS = [
  'Discovering my Higher Life Purpose & Soul Mission',
  'Navigating Deep Career & Vocation Crossroads',
  'Deepening Romantic Harmony & Soulmate Dynamics',
  'Unlocking Creative Mastery & Financial Flow',
  'Emotional Healing & Shadow Integration',
  'Harnessing Intuition & Daily Spiritual Discipline',
];

export const SPREAD_CONFIGS: SpreadConfig[] = [
  {
    id: 'single_card',
    title: 'Daily Oracle Pulse',
    subtitle: '1 Card · Instant Alignment',
    description: 'A focused single oracle transmission providing acute daily clarity, energetic focal point, and immediate actionable counsel.',
    card_count: 1,
    icon_name: 'Sparkles',
    positions: [
      {
        index: 0,
        label: 'The Focal Oracle',
        meaning: 'The dominant cosmic frequency influencing your present moment.',
      },
    ],
    suitability: ['Quick clarity', 'Morning reflection', 'Daily decision guidance'],
  },
  {
    id: 'three_card',
    title: 'Temporal Trinity',
    subtitle: '3 Cards · Past, Present & Horizon',
    description: 'The classic tripartite lens revealing how karmic foundations shape your current reality and where momentum is directing your path.',
    card_count: 3,
    icon_name: 'Orbit',
    positions: [
      { index: 0, label: 'Root / Karmic Past', meaning: 'Subconscious foundation, past catalyst, or unresolved lesson.' },
      { index: 1, label: 'Apex / Present Reality', meaning: 'Current energetic state, immediate challenge, or active lesson.' },
      { index: 2, label: 'Horizon / Emerging Future', meaning: 'Projected outcome if current trajectory and conscious action persist.' },
    ],
    suitability: ['General guidance', 'Timeflow analysis', 'Decision crossroads'],
  },
  {
    id: 'relationship',
    title: 'Soul Mirror & Dynamics',
    subtitle: '4 Cards · Relational Harmony',
    description: 'An intimate architectural breakdown of two energetic fields—your perspective, their resonance, the bridge between, and the higher growth catalyst.',
    card_count: 4,
    icon_name: 'HeartHandshake',
    positions: [
      { index: 0, label: 'Your Energy Field', meaning: 'Your conscious and unconscious emotional posture.' },
      { index: 1, label: 'The Partner Resonance', meaning: 'Their current frequency, unspoken needs, or projection.' },
      { index: 2, label: 'The Alchemy / Dynamic', meaning: 'The interactive tension, friction, or chemistry uniting you.' },
      { index: 3, label: 'The Evolutionary Path', meaning: 'The highest mutual lesson and relational outcome.' },
    ],
    suitability: ['Romantic bonds', 'Partnerships', 'Conflict resolution'],
  },
  {
    id: 'career',
    title: 'Vocation & Abundance Matrix',
    subtitle: '5 Cards · Purpose & Prosperity',
    description: 'Strategic cosmic alignment for professional mastery, identifying hidden talents, material blockages, and high-impact pivot windows.',
    card_count: 5,
    icon_name: 'Compass',
    positions: [
      { index: 0, label: 'Core Vocation Archetype', meaning: 'Your authentic innate strengths and creative mastery.' },
      { index: 1, label: 'Current Economic Vector', meaning: 'The present professional climate and energetic capital.' },
      { index: 2, label: 'Hidden Blockage / Shadow', meaning: 'Subconscious fears, impostor syndrome, or structural friction.' },
      { index: 3, label: 'Strategic Leverage Point', meaning: 'The exact pivot or skill required for breakthrough.' },
      { index: 4, label: 'Abundance Horizon', meaning: 'The financial and reputational manifestation awaiting.' },
    ],
    suitability: ['Career transitions', 'Business strategy', 'Wealth manifestation'],
  },
  {
    id: 'celtic_cross',
    title: 'Grand Celtic Cross',
    subtitle: '10 Cards · Deep Holistic Archetype',
    description: 'The revered ancient 10-point metaphysical cartography delivering an all-encompassing revelation of conscious, subconscious, and destiny forces.',
    card_count: 10,
    icon_name: 'Crown',
    positions: [
      { index: 0, label: 'Heart of the Matter', meaning: 'The essential core of the current situation.' },
      { index: 1, label: 'Crossing Force / Challenge', meaning: 'The immediate obstacle or friction point.' },
      { index: 2, label: 'Subconscious Root', meaning: 'Deep psychological foundation and hidden motives.' },
      { index: 3, label: 'Passing Influences', meaning: 'What is receding from your life cycle.' },
      { index: 4, label: 'Conscious Aspirations', meaning: 'Your crown goal, ideal, and higher thought.' },
      { index: 5, label: 'Imminent Horizon', meaning: 'What approaches in the immediate near-future.' },
      { index: 6, label: 'Self-Perception & Stance', meaning: 'Your internal attitude and spiritual posture.' },
      { index: 7, label: 'External Environment', meaning: 'The people, forces, and atmospheric energies around you.' },
      { index: 8, label: 'Hopes & Vulnerabilities', meaning: 'Your secret desires, anxieties, and reservations.' },
      { index: 9, label: 'Ultimate Synthesis', meaning: 'The holistic culmination and destiny trajectory.' },
    ],
    suitability: ['Deep spiritual audit', 'Life milestone readings', 'Complex multi-factor inquiries'],
  },
  {
    id: 'life_path',
    title: 'Destiny Helix & Life Path',
    subtitle: '6 Cards · Soul Blueprint Evolution',
    description: 'Harmonizes palm-line bio-geometry with archetypal soul contracts across your incarnation’s past, present, and pinnacle realizations.',
    card_count: 6,
    icon_name: 'Infinity',
    positions: [
      { index: 0, label: 'Primal Soul Imprint', meaning: 'Inherent gifts and ancient karmic conditioning.' },
      { index: 1, label: 'Current Phase of Mastery', meaning: 'The test of character you are currently refining.' },
      { index: 2, label: 'The Heart Gate (Emotion)', meaning: 'Your emotional frequency and empathy capacity.' },
      { index: 3, label: 'The Mind Citadel (Intellect)', meaning: 'Your mental clarity, strategy, and vision.' },
      { index: 4, label: 'The Fate Conduit (Destiny)', meaning: 'The alignment between free will and divine timing.' },
      { index: 5, label: 'The Transcendence Apex', meaning: 'Your spiritual legacy and highest conscious evolution.' },
    ],
    suitability: ['Life purpose discovery', 'Spiritual awakening', 'Long-term destiny navigation'],
  },
];

export const TAROT_DECK: TarotCardData[] = [
  {
    id: 'the-fool',
    name: '0 · The Fool',
    arcana: 'major',
    number: 0,
    element: 'Air',
    keywords: ['Innocence', 'New Beginnings', 'Spontaneous Faith', 'Infinite Potential'],
    upright_meaning: 'A leap of pure faith into the unknown. Boundless enthusiasm, fresh beginnings, and freedom from dogma.',
    reversed_meaning: 'Recklessness, fear of taking calculated risks, or leaping without intuitive grounding.',
    symbolism: 'A traveler stepping off a cliff bathed in celestial light, guided by a white dog of instinct.',
    astrological_association: 'Uranus (Divine Freedom)',
  },
  {
    id: 'the-magician',
    name: 'I · The Magician',
    arcana: 'major',
    number: 1,
    element: 'Air',
    keywords: ['Manifestation', 'Resourcefulness', 'Willpower', 'Alchemical Power'],
    upright_meaning: 'As above, so below. You possess every elemental tool (Wands, Cups, Swords, Pentacles) to manifest your divine intention into physical form.',
    reversed_meaning: 'Untapped potential, deceptive illusions, manipulated energies, or misdirected willpower.',
    symbolism: 'An alchemist with infinity symbol overhead, channeling cosmic fire into earthly vessels.',
    astrological_association: 'Mercury (Mind & Alchemy)',
  },
  {
    id: 'the-high-priestess',
    name: 'II · The High Priestess',
    arcana: 'major',
    number: 2,
    element: 'Water',
    keywords: ['Intuition', 'Sacred Mystery', 'Subconscious Mind', 'Divine Feminine'],
    upright_meaning: 'The veil between the visible and invisible worlds. Trust your inner knowing, vivid dreams, and subtle synchronicity.',
    reversed_meaning: 'Ignoring inner whispers, superficial gossip, repressed instincts, or emotional disconnect.',
    symbolism: 'Seated between the pillars of Solomon (Boaz and Jachin) with a crescent moon at her feet.',
    astrological_association: 'Moon (Subconscious Waters)',
  },
  {
    id: 'the-empress',
    name: 'III · The Empress',
    arcana: 'major',
    number: 3,
    element: 'Earth',
    keywords: ['Abundance', 'Fertility', 'Sensory Grace', 'Creative Nurturing'],
    upright_meaning: 'Unbounded creative germination and sensual harmony. Ideas flourish in rich soil; love and prosperity blossom.',
    reversed_meaning: 'Creative stagnation, smothering codependency, depletion of vitality, or neglected self-care.',
    symbolism: 'A serene queen crowned with twelve stars amidst golden wheat fields and flowing waterfalls.',
    astrological_association: 'Venus (Grace & Beauty)',
  },
  {
    id: 'the-emperor',
    name: 'IV · The Emperor',
    arcana: 'major',
    number: 4,
    element: 'Fire',
    keywords: ['Sovereignty', 'Structure', 'Authority', 'Strategic Mastery'],
    upright_meaning: 'Mastery over the physical plane through disciplined architecture, clear boundaries, and decisive leadership.',
    reversed_meaning: 'Rigid tyranny, loss of control, disorganized chaos, or resistance to reasonable order.',
    symbolism: 'A majestic ruler on a stone throne carved with ram heads, holding the globe and scepter.',
    astrological_association: 'Aries (Cosmic Will)',
  },
  {
    id: 'the-hierophant',
    name: 'V · The Hierophant',
    arcana: 'major',
    number: 5,
    element: 'Earth',
    keywords: ['Spiritual Tradition', 'Sacred Lore', 'Guidance', 'Moral Code'],
    upright_meaning: 'Bridging timeless ancestral wisdom with modern practice. Initiation into higher spiritual knowledge and ethical clarity.',
    reversed_meaning: 'Dogmatic rigidity, blind obedience, challenging outmoded orthodoxy, or finding personal inner truth.',
    symbolism: 'A spiritual mentor flanked by crossed golden keys of revelation and two initiates.',
    astrological_association: 'Taurus (Sacred Earth)',
  },
  {
    id: 'the-lovers',
    name: 'VI · The Lovers',
    arcana: 'major',
    number: 6,
    element: 'Air',
    keywords: ['Soul Alignment', 'Harmonic Union', 'Values Crossroads', 'Dual Transcendence'],
    upright_meaning: 'Deep soul resonance and conscious alignment of choices. Unifying the masculine and feminine polarities within and without.',
    reversed_meaning: 'Inner conflict, fractured communication, misalignment of core principles, or fear of vulnerability.',
    symbolism: 'Archangel Raphael showering golden grace over the sacred union of twin souls.',
    astrological_association: 'Gemini (Divine Polarity)',
  },
  {
    id: 'the-chariot',
    name: 'VII · The Chariot',
    arcana: 'major',
    number: 7,
    element: 'Water',
    keywords: ['Triumph', 'Focus', 'Conquering Opposites', 'Unyielding Drive'],
    upright_meaning: 'Harmonizing conflicting drives (the black and white sphinxes) through sheer focus and unwavering determination to claim victory.',
    reversed_meaning: 'Loss of direction, aggression, burnout, feeling overpowered by circumstances.',
    symbolism: 'A crowned armored warrior riding a celestial canopy chariot drawn by twin sphinxes.',
    astrological_association: 'Cancer (Emotional Armor)',
  },
  {
    id: 'strength',
    name: 'VIII · Strength',
    arcana: 'major',
    number: 8,
    element: 'Fire',
    keywords: ['Gentle Mastery', 'Compassion', 'Courage', 'Shadow Taming'],
    upright_meaning: 'True power is soft, patient, and compassionate. Taming raw instinctual passions not by force, but through unconditional grace.',
    reversed_meaning: 'Self-doubt, explosive reactivity, fatigue, or succumbing to primal insecurities.',
    symbolism: 'A maiden adorned with flowers gently closing the jaws of a roaring golden lion.',
    astrological_association: 'Leo (The Regal Heart)',
  },
  {
    id: 'the-hermit',
    name: 'IX · The Hermit',
    arcana: 'major',
    number: 9,
    element: 'Earth',
    keywords: ['Introspection', 'Solitary Lantern', 'Inner Sage', 'Deep Reflection'],
    upright_meaning: 'Retreating from outer noise to illuminate the sacred cavern of the soul. The lantern of wisdom shines one step at a time.',
    reversed_meaning: 'Unhealthy isolation, bitter loneliness, stubborn detachment, or fear of returning to community.',
    symbolism: 'An ancient cloaked sage atop a snow-capped peak holding the six-pointed star lantern.',
    astrological_association: 'Virgo (Purified Wisdom)',
  },
  {
    id: 'wheel-of-fortune',
    name: 'X · Wheel of Fortune',
    arcana: 'major',
    number: 10,
    element: 'Fire',
    keywords: ['Karma', 'Cycles of Destiny', 'Synchronicity', 'Pivotal Turning Point'],
    upright_meaning: 'The great cosmic wheel turns in your favor. Sudden serendipity, karmic milestones, and aligning with universal rhythms.',
    reversed_meaning: 'Resisting natural cycles, setbacks, or a perceived spell of friction that invites deeper humility.',
    symbolism: 'A rotating wheel inscribed with TARO/ROTA surrounded by the four living celestial creatures.',
    astrological_association: 'Jupiter (Expansive Fortune)',
  },
  {
    id: 'justice',
    name: 'XI · Justice',
    arcana: 'major',
    number: 11,
    element: 'Air',
    keywords: ['Karmic Balance', 'Truth', 'Equilibrium', 'Integrity'],
    upright_meaning: 'Unvarnished truth and karmic equilibrium. Decisions made with impeccable integrity will yield righteous outcomes.',
    reversed_meaning: 'Dishonesty, unfair treatment, accountability evasion, or harsh self-condemnation.',
    symbolism: 'A crowned figure holding upright double-edged sword of discernment and golden scales of truth.',
    astrological_association: 'Libra (Cosmic Scales)',
  },
  {
    id: 'the-hanged-man',
    name: 'XII · The Hanged Man',
    arcana: 'major',
    number: 12,
    element: 'Water',
    keywords: ['Perspective Shift', 'Surrender', 'Sacred Pause', 'Enlightenment'],
    upright_meaning: 'Surrendering egoic control to gain celestial illumination. In stillness, what seemed impossible reveals its true nature.',
    reversed_meaning: 'Futile martyrdom, stubborn resistance to necessary change, stalling out of fear.',
    symbolism: 'Suspended upside-down by one foot from the living World Tree with a halo of golden epiphany.',
    astrological_association: 'Neptune (Mystic Surrender)',
  },
  {
    id: 'death',
    name: 'XIII · Death & Rebirth',
    arcana: 'major',
    number: 13,
    element: 'Water',
    keywords: ['Metamorphosis', 'Shedding the Old', 'Profound Rebirth', 'Inevitable Transition'],
    upright_meaning: 'The necessary decay of the obsolete so the radiant new self can arise. A glorious phoenix transition.',
    reversed_meaning: 'Clinging desperately to rotting dynamics, fear of transformation, prolonged stagnation.',
    symbolism: 'A skeletal rider carrying the mystic white rose flag as the dawn sun rises between twin towers.',
    astrological_association: 'Scorpio (Alchemical Death)',
  },
  {
    id: 'temperance',
    name: 'XIV · Temperance',
    arcana: 'major',
    number: 14,
    element: 'Fire',
    keywords: ['Alchemy', 'Equilibrium', 'Patience', 'Divine Synergy'],
    upright_meaning: 'Blending opposing energies into a golden elixir. Patience, moderation, and the quiet magic of harmonious integration.',
    reversed_meaning: 'Imbalance, reckless extremes, clashing agendas, or rushing processes that require slow brewing.',
    symbolism: 'A winged angel pouring water and fire essence continuously between two golden urns.',
    astrological_association: 'Sagittarius (Higher Synthesis)',
  },
  {
    id: 'the-star',
    name: 'XVII · The Star',
    arcana: 'major',
    number: 17,
    element: 'Air',
    keywords: ['Hope', 'Cosmic Inspiration', 'Spiritual Rejuvenation', 'Serenity'],
    upright_meaning: 'After every storm, the celestial star emerges. Crystal-clear guidance, serene peace, and renewed faith in your destiny.',
    reversed_meaning: 'Temporary despair, disillusionment, losing sight of personal light, cynical resignation.',
    symbolism: 'A maiden pouring crystalline waters onto land and pool beneath eight radiating radiant stars.',
    astrological_association: 'Aquarius (The Water Bearer)',
  },
  {
    id: 'the-moon',
    name: 'XVIII · The Moon',
    arcana: 'major',
    number: 18,
    element: 'Water',
    keywords: ['Subconscious Depth', 'Illusions', 'Psychic Visions', 'Night Journey'],
    upright_meaning: 'Traversing the misty twilight landscape of dreams, deep intuition, and ancestral instincts. Not all is as it seems—trust the night compass.',
    reversed_meaning: 'Confusion dissolving into clarity, releasing paranoia, unmasking hidden deception.',
    symbolism: 'A full moon shedding drops of dew between twin towers as a dog and wolf howl.',
    astrological_association: 'Pisces (The Deep Oceanic Psyche)',
  },
  {
    id: 'the-sun',
    name: 'XIX · The Sun',
    arcana: 'major',
    number: 19,
    element: 'Fire',
    keywords: ['Radiance', 'Unbridled Joy', 'Vitality', 'Supreme Success'],
    upright_meaning: 'The purest golden blessing of the deck. Undiluted clarity, vibrant health, triumphant celebration, and joyful abundance.',
    reversed_meaning: 'Temporary cloud cover over joy, delayed gratification, need for inner warmth.',
    symbolism: 'A joyful child riding a white horse beneath a giant smiling radiant sun with sunflowers.',
    astrological_association: 'Sun (Solar Sovereignty)',
  },
  {
    id: 'the-world',
    name: 'XXI · The World',
    arcana: 'major',
    number: 21,
    element: 'Earth',
    keywords: ['Wholeness', 'Culmination', 'Cosmic Integration', 'Mastery'],
    upright_meaning: 'The great cycle completes. Total synthesis, universal connection, and entering the highest octave of your soul journey.',
    reversed_meaning: 'Near completion requiring one final push, lingering loose ends, fear of graduation.',
    symbolism: 'A dancer enclosed in a laurel wreath of victory, flanked by the four cardinal astrological beings.',
    astrological_association: 'Saturn (Sacred Completion)',
  },
  {
    id: 'ace-of-wands',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    element: 'Fire',
    keywords: ['Primal Spark', 'Inspiration', 'Bold Initiative', 'Creative Fire'],
    upright_meaning: 'A divine burst of fiery inspiration and creative impetus.',
    reversed_meaning: 'Delays, lack of direction, creative block, burning out prematurely.',
    symbolism: 'A celestial hand emerging from clouds grasping a blossoming staff of fire.',
    astrological_association: 'Root of Fire',
  },
  {
    id: 'ace-of-cups',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    element: 'Water',
    keywords: ['Emotional Awakening', 'Overflowing Love', 'Intuitive Grace', 'Peace'],
    upright_meaning: 'The fountain of unconditional love and spiritual receptivity.',
    reversed_meaning: 'Blocked emotions, vulnerability hesitation, drained heart energy.',
    symbolism: 'A golden chalice overflowing with five streams of living water into a lotus lake.',
    astrological_association: 'Root of Water',
  },
  {
    id: 'ace-of-swords',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    element: 'Air',
    keywords: ['Mental Breakthrough', 'Absolute Clarity', 'Truth Unveiled', 'Discernment'],
    upright_meaning: 'A lightning bolt of intellectual breakthrough and sharp, piercing truth.',
    reversed_meaning: 'Mental confusion, harsh judgment, miscommunication, chaotic thinking.',
    symbolism: 'An upright celestial broadsword crowned with olive and palm branches.',
    astrological_association: 'Root of Air',
  },
  {
    id: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    element: 'Earth',
    keywords: ['Material Manifestation', 'Prosperity Seed', 'Grounded Stability', 'Tangible Wealth'],
    upright_meaning: 'A golden seed of tangible wealth, physical health, and enduring earthly success.',
    reversed_meaning: 'Missed financial opportunity, poor resource allocation, ungrounded plans.',
    symbolism: 'A radiant hand presenting a golden coin in an archway garden of lush roses and lilies.',
    astrological_association: 'Root of Earth',
  },
];

export const PALM_PRESETS = [
  {
    id: 'mystic_visionary',
    title: 'The Mystic Visionary',
    tagline: 'Deep curved heart line & extended intuitive line of Luna',
    image_url: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=800',
    description: 'Archetype characterized by high emotional depth, visionary creative instincts, and a strong Mount of Apollo.',
  },
  {
    id: 'strategic_alchemist',
    title: 'The Strategic Alchemist',
    tagline: 'Straight fork head line & prominent Jupiter mount',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    description: 'High analytical precision, strong sovereign leadership, and deep capacity for material manifestation.',
  },
  {
    id: 'healer_empath',
    title: 'The Harmonic Healer',
    tagline: 'Long sweeping life line & chained empathetic heart line',
    image_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800',
    description: 'Tremendous empathy, somatic intuition, nurturing energy, and high relational sensitivity.',
  },
];
